name: 'Close stale pull requests'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    if: ${{ github.repository_owner == 'pytorch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-pr-message: >
            \## Stale alert!
            Looks like this PR hasn't been updated in a while so we're going to go ahead and mark this as `Stale`. <br>
            Feel free to remove the `Stale` label if you feel this was a mistake. <br>
            `Stale` pull requests will automatically be closed 30 days after being marked `Stale` <br>
          exempt-pr-labels: "no-stale,open source,high priority"
          days-before-stale: 60
          days-before-close: 90
  stale-open-source:
    if: ${{ github.repository_owner == 'pytorch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-pr-message: >
            \## Stale alert!
            Looks like this PR hasn't been updated in a while so we're going to go ahead and mark this as `Stale`. <br>
            Feel free to remove the `Stale` label if you feel this was a mistake. <br>
            If you are unable to remove the `Stale` label please contact a maintainer in order to do so. <br>
            `Stale` pull requests will automatically be closed 30 days after being marked `Stale` <br>
          exempt-pr-labels: "no-stale,high priority"
          only-labels: "open source"
          days-before-stale: 150
          days-before-close: 180
